name: CD - Development

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy to Render (Dev)
    runs-on: ubuntu-latest
    environment: develop  # Injects environment-level secrets

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEV }}
          echo "Deployment to Development triggered at $(date)" 